os: linux
dist: bionic

language: python
python:
  - 3.6
  - 3.7
  - 3.8

env:
  - SUITE=UNIT COVERAGE=OFF
  - SUITE=UNIT COVERAGE=ON
  - SUITE=SYSTEM

notifications:
  email:
    recipients:
      - support@fitbenchmarking.com
    on_success: never
    on_failure: always


before_install:
  # Adding RALfit packages
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install lcov
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev

  # Adding gsl pacakges
  - sudo apt-get install gsl-bin
  - sudo apt-get install libgsl-dev
  - sudo apt-get install libgsl-dbg


install:
  # Builds RALfit
  - ./build_ralfit.sh
    # To access RALfit
  - export LD_LIBRARY_PATH=$HOME/build/fitbenchmarking/fitbenchmarking/RALFit/libRALFit/build/src:$LD_LIBRARY_PATH

    # Builds cutest
  - source build_cutest.sh
    # to access cutest
  - export PATH="${SIFDECODE}/bin:${CUTEST}/bin:$PATH"
  # let's ensure the environment variables are set
  - export ARCHDEFS=$HOME/cutest/archdefs/
  - export SIFDECODE=$HOME/cutest/sifdecode/
  - export MASTSIF=$HOME/cutest/cutest/sif/
  - export CUTEST=$HOME/cutest/cutest/
  - export MYARCH="pc64.lnx.gfo"	
  
  - pip install -r requirements.txt
  - pip install .
  - python3 setup.py externals

  - export PYTHONPATH=$PYTHONPATH:/opt/mantidnightly-python3/lib:/opt/mantidnightly-python3/bin

  # Python bindings for GSL and CUTEst
  - pip install pygsl
  - pip install pycutest

script:
  - if [[ $SUITE == "UNIT" ]]; then ./travis/unit_tests.sh  ; fi
  - if [[ $SUITE == "SYSTEM" ]]; then ./travis/system_tests.sh  ; fi

after_success:
  - if [[ $COVERAGE == "ON" ]]; then coveralls; fi


jobs:
  exclude:
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.6
    - env: SUITE=UNIT COVERAGE=ON
      python: 3.7
    - env: SUITE=UNIT COVERAGE=ON
      python: 3.8
    - env: SUITE=SYSTEM
      python: 3.7
    - env: SUITE=SYSTEM
      python: 3.8
  # Allow failures as we dont have a mantid build on these python versions
  allow-failures:
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.7
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.8
