sudo: required
language: python
python:
  - "2.7"
dist: xenial
virtualenv:
  system_site_packages: true

notifications:
  email:
    recipients:
      - support@fitbenchmarking.com
    on_success: never
    on_failure: always

stages:
  - name: Tests
  - name: SysTests
    if: type = cron

before_install:
  # Adding RALfit packages
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install lcov
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  # Adding gsl pacakges
  - sudo apt-get install gsl-bin
  - sudo apt-get install libgsl-dev
  - sudo apt-get install libgsl-dbg

  - sudo apt-get install pandoc

install:
  # Builds RALfit
  - ./build_ralfit.sh

  - pip install -r requirements.txt
  - pip install .
  - python setup.py externals

  # To access RALfit
  - export LD_LIBRARY_PATH=$HOME/build/fitbenchmarking/fitbenchmarking/RALFit/libRALFit/build/src:$LD_LIBRARY_PATH


jobs:
  include:
    - stage: Tests
      before_script: python -m mantid.simpleapi || true
      script:
        # ======= Examples Tests =============== #
        - pytest fitbenchmarking/cli --cov=fitbenchmarking/cli
          --cov-report term-missing
        # ======= Fitting Tests =============== #
        - pytest fitbenchmarking/fitting/ --cov=fitbenchmarking/fitting/
          --cov-report term-missing --cov-append
        # ======= Parsing Tests =============== #
        - pytest fitbenchmarking/parsing/tests/ --cov=fitbenchmarking/parsing/
          --cov-report term-missing --cov-append
        # ======= Utils Tests =============== #
        - pytest fitbenchmarking/utils/tests/ --cov=fitbenchmarking/utils/
          --cov-report term-missing --cov-append
      after_success:
        - coveralls
  allow_failures:
    - stage: SysTests
      before_script: python -m mantid.simpleapi || true
      script:
        # ======= System Test =============== #
        - cd fitbenchmarking/systests
        - python generate_current_results.py
        - python tbl_comparison.py
