sudo: required
language: python
python:
  - "2.7"
dist: trusty
virtualenv:
  system_site_packages: true


stages:
  - name: Tests
  - name: SysTests
    if: type = cron

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib h5py yaml ipython
install:
  - python setup.py install
  - python setup.py externals

jobs:
  include:
    - stage: Tests
      before_script: mantidpython -m mantid.simpleapi || true
      # ======= Fitting Tests =============== #
      script: mantidpython fitbenchmarking/fitting/tests/fit_algorithms_tests.py
      script: mantidpython fitbenchmarking/fitting/tests/mantid_utils_tests.py
      # ======= Parsing Tests =============== #
      script: python fitbenchmarking/parsing/tests/fetch_data_tests.py
      script: python fitbenchmarking/parsing/tests/parse_neutron_tests.py
      script: python fitbenchmarking/parsing/tests/parse_nist_tests.py
      # ======= Result Processing Tests =============== #
      script: python fitbenchmarking/result_processing/tests/fitdetails_tbls_tests.py
      script: python fitbenchmarking/result_processing/tests/misc_tests.py
      script: python fitbenchmarking/result_processing/tests/numpy_restables_tests.py
      script: python fitbenchmarking/result_processing/tests/rst_table_tests.py
      # ======= Utils Tests =============== #
      script: python fitbenchmarking/utils/tests/fit_misc_tests.py

    - stage: SysTests
      script:
        # ======= System Test =============== #
        - mantidpython system_tests/generate_current_resuts.py
        - mantidpython system_tests/system_test.py

