sudo: required
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

dist: trusty

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib h5py yaml ipython
install:
  - python setup.py install
  - python setup.py externals

before_script:
  - mantidpython fitbenchmarking/fitting/tests/fit_algorithms_tests.py || true
  - mantidpython fitbenchmarking/fitting/tests/mantid_utils_tests.py || true
script:
  # ======= Fitting Tests =============== #
  - mantidpython fitbenchmarking/fitting/tests/fit_algorithms_tests.py
  - mantidpython fitbenchmarking/fitting/tests/mantid_utils_tests.py
  # ======= Parsing Tests =============== #
  - python fitbenchmarking/parsing/tests/fetch_data_tests.py
  - python fitbenchmarking/parsing/tests/parse_neutron_tests.py
  - python fitbenchmarking/parsing/tests/parse_nist_tests.py
  # ======= Result Processing Tests =============== #
  - python fitbenchmarking/result_processing/tests/fitdetails_tbls_tests.py
  - python fitbenchmarking/result_processing/tests/misc_tests.py
  - python fitbenchmarking/result_processing/tests/numpy_restables_tests.py
  - python fitbenchmarking/result_processing/tests/rst_table_tests.py
  # ======= Utils Tests =============== #
  - python fitbenchmarking/utils/tests/fit_misc_tests.py
