os: linux
dist: bionic

language: python
python:
  - 3.6
  - 2.7
  - 3.7
  - 3.8

env:
  - SUITE=UNIT COVERAGE=OFF
  - SUITE=UNIT COVERAGE=ON
  - SUITE=SYSTEM
  - SUITE=LINTING


notifications:
  email:
    recipients:
      - support@fitbenchmarking.com
    on_success: never
    on_failure: always


before_install:
  # Adding RALfit packages
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install lcov
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev

  # Adding gsl pacakges
  - sudo apt-get install gsl-bin
  - sudo apt-get install libgsl-dev
  - sudo apt-get install libgsl-dbg


install:
  - if [[ $SUITE == "UNIT" ]]; then source ./travis/full_install.sh; fi
  - if [[ $SUITE == "SYSTEM" ]]; then source ./travis/full_install.sh; fi
  - if [[ $SUITE == "LINTING" ]]; then source ./travis/linting_install.sh; fi

script:
  - if [[ $SUITE == "UNIT" ]]; then ./travis/unit_tests.sh; fi
  - if [[ $SUITE == "SYSTEM" ]]; then ./travis/system_tests.sh; fi
  - if [[ $SUITE == "LINTING" ]]; then ./travis/linting_tests.sh;  fi

after_success:
  - if [[ $COVERAGE == "ON" ]]; then coveralls; fi

jobs:
  exclude:
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.6
    - env: SUITE=UNIT COVERAGE=ON
      python: 2.7
    - env: SUITE=UNIT COVERAGE=ON
      python: 3.7
    - env: SUITE=UNIT COVERAGE=ON
      python: 3.8
    - env: SUITE=SYSTEM
      python: 2.7
    - env: SUITE=SYSTEM
      python: 3.7
    - env: SUITE=SYSTEM
      python: 3.8
    - env: SUITE=LINTING
      python: 3.6
    - env: SUITE=LINTING
      python: 3.7
      
  allow_failures:
    # No longer guaranteed but good to know if working.
    - env: SUITE=UNIT COVERAGE=OFF
      python: 2.7
    - env: SUITE=LINTING
      python: 2.7
    # Allow failures as we dont have a mantid build on these python versions
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.7
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.8
