sudo: required
language: python
python:
  - "2.7"
dist: trusty
virtualenv:
  system_site_packages: true


stages:
  - name: Tests
  - name: SysTests
    if: type = cron

before_install:
  # Coverage pre-requisites
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  # Dependencies like matplotlib, scipy, numpy etc.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib h5py yaml ipython
install:
  - python setup.py install
  - python setup.py externals

jobs:
  include:
    - stage: Tests
      before_script: mantidpython -m mantid.simpleapi || true
      script:
        - nosetests --with-coverage
      after_success:
        - coveralls

    - stage: SysTests
      before_script: mantidpython -m mantid.simpleapi || true
      script:
        # ======= System Test =============== #
        - mantidpython system_tests/generate_current_results.py
        - mantidpython system_tests/system_test.py

