sudo: required
language: python
python:
  - "2.7"
dist: xenial
virtualenv:
  system_site_packages: true

notifications:
  email:
    recipients:
      - support@fitbenchmarking.com
    on_success: never
    on_failure: always

stages:
  - name: Tests

before_install:
  # Adding RALfit packages
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install lcov
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install pandoc

install:
  # Builds RALfit
  - ./build_ralfit.sh

  - pip install -r requirements.txt
  - python setup.py install
  - python setup.py externals

  # To access RALfit
  - export LD_LIBRARY_PATH=$HOME/build/fitbenchmarking/fitbenchmarking/RALFit/libRALFit/build/src:$LD_LIBRARY_PATH


jobs:
  include:
    - stage: Tests
      name: Unit Tests
      script:
        # ======= Examples Tests =============== #
        - pytest fitbenchmarking/cli --cov=fitbenchmarking/cli
          --cov-report term-missing
        # ======= Fitting Tests =============== #
        - pytest fitbenchmarking/fitting/ --cov=fitbenchmarking/fitting/
          --cov-report term-missing --cov-append
        # ======= Parsing Tests =============== #
        - pytest fitbenchmarking/parsing/tests/ --cov=fitbenchmarking/parsing/
          --cov-report term-missing --cov-append
        # ======= Result Processing Tests =============== #
        - pytest fitbenchmarking/resproc/tests/
          --cov=fitbenchmarking/resproc --cov-report term-missing
          --cov-append
        # ======= Utils Tests =============== #
        - pytest fitbenchmarking/utils/tests/ --cov=fitbenchmarking/utils/
          --cov-report term-missing --cov-append
    - name: Integration Tests
      script:
        # ======= System Test =============== #
        - pytest fitbenchmarking/systests
