sudo: required
language: python
python:
  - "2.7"

install:
  - python setup.py install
  - python setup.py externals
  - ls /opt/Mantid/bin

before_script:
  sudo: false
  - export PYTHONPATH=$PYTHONPATH:{/opt/Mantid/bin}

script:
  sudo: false
  # ======= Fitting Tests =============== #
  - python fitbenchmarking/fitting/tests/fit_algorithms_tests.py
  - python fitbenchmarking/fitting/tests/mantid_utils_tests.py
  # ======= Parsing Tests =============== #
  - python fitbenchmarking/parsing/tests/fetch_data_tests.py
  - python fitbenchmarking/parsing/tests/parse_neutron_tests.py
  - python fitbenchmarking/parsing/tests/parse_nist_tests.py
  # ======= Result Processing Tests =============== #
  - python fitbenchmarking/result_processing/tests/fitdetails_tbls_tests.py
  - python fitbenchmarking/result_processing/tests/misc_tests.py
  - python fitbenchmarking/result_processing/tests/numpy_restables_tests.py
  - python fitbenchmarking/result_processing/tests/rst_table_tests.py
  # ======= Utils Tests =============== #
  - python fitbenchmarking/utils/tests/fit_misc_tests.py
