os: linux
dist: bionic

language: python
python:
  - 3.6
  - 3.7
  - 3.8

env:
  - SUITE=UNIT COVERAGE=ON
  - SUITE=UNIT_DEFAULT COVERAGE=OFF
  - SUITE=SYSTEM
  - SUITE=LINTING


notifications:
  email:
    recipients:
      - support@fitbenchmarking.com
    on_success: never
    on_failure: always


before_install:
  - sudo apt-get update

install:
  - if [[ $SUITE == "UNIT" ]]; then source ./travis/full_install.sh; fi
  - if [[ $SUITE == "UNIT_DEFAULT" ]]; then source ./travis/default_install.sh; fi
  - if [[ $SUITE == "SYSTEM" ]]; then source ./travis/full_install.sh; fi
  - if [[ $SUITE == "LINTING" ]]; then source ./travis/linting_install.sh; fi

script:
  - if [[ $SUITE == "UNIT" ]]; then source ./travis/unit_tests.sh; fi
  - if [[ $SUITE == "UNIT_DEFAULT" ]]; then ./travis/unit_tests_default.sh; fi
  - if [[ $SUITE == "SYSTEM" ]]; then ./travis/system_tests.sh; fi
  - if [[ $SUITE == "LINTING" ]]; then ./travis/linting_tests.sh;  fi

after_success:
  - if [[ $COVERAGE == "ON" ]]; then coveralls; fi

jobs:
  exclude:
    - env: SUITE=UNIT COVERAGE=OFF
      python: 3.6
    - env: SUITE=UNIT_DEFAULT COVERAGE=OFF
      python: 3.6
    - env: SUITE=UNIT COVERAGE=ON
      python: 3.7
    - env: SUITE=UNIT COVERAGE=ON
      python: 3.8
    - env: SUITE=SYSTEM
      python: 3.7
    - env: SUITE=SYSTEM
      python: 3.8
    - env: SUITE=LINTING
      python: 3.6
    - env: SUITE=LINTING
      python: 3.7

