sudo: required
language: python
python:
  - "2.7"
dist: xenial
virtualenv:
  system_site_packages: true

notifications:
  email:
    recipients:
      - support@fitbenchmarking.com
    on_success: never
    on_failure: always

stages:
  - name: Tests

before_install:
  # Adding RALfit packages
  - sudo apt-get update
  - sudo apt-get install gfortran
  - sudo apt-get install lcov
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev

  # Adding gsl pacakges
  - sudo apt-get install gsl-bin
  - sudo apt-get install libgsl-dev
  - sudo apt-get install libgsl-dbg


install:
  # Builds RALfit
  - ./build_ralfit.sh
    # To access RALfit
  - export LD_LIBRARY_PATH=$HOME/build/fitbenchmarking/fitbenchmarking/RALFit/libRALFit/build/src:$LD_LIBRARY_PATH

    # Builds cutest
  - source build_cutest.sh
    # to access cutest
  - export PATH="${SIFDECODE}/bin:${CUTEST}/bin:$PATH"
  # let's ensure the environment variables are set
  - export ARCHDEFS=$HOME/cutest/archdefs/
  - export SIFDECODE=$HOME/cutest/sifdecode/
  - export MASTSIF=$HOME/cutest/cutest/sif/
  - export CUTEST=$HOME/cutest/cutest/
  - export MYARCH="pc64.lnx.gfo"	
  
  - pip install -r requirements.txt
  - pip install .
  - python setup.py externals

  # To access RALfit
  - export LD_LIBRARY_PATH=$HOME/build/fitbenchmarking/fitbenchmarking/RALFit/libRALFit/build/src:$LD_LIBRARY_PATH

  # Python bindings for GSL
  # --force seems to be necessary to link numpy
  - pip install pygsl --force

  - pip install pycutest
  - pip install backports.tempfile


jobs:
  include:
    - stage: Tests
      name: Unit Tests
      script:
        # ======= Examples Tests =============== #
        - pytest fitbenchmarking/cli --cov=fitbenchmarking/cli
          --cov-report term-missing
        # ======= Fitting Tests =============== #
        - pytest fitbenchmarking/controllers --cov=fitbenchmarking/controllers
          --cov-report term-missing --cov-append
        # ======= Parsing Tests =============== #
        - pytest fitbenchmarking/parsing --cov=fitbenchmarking/parsing
          --cov-report term-missing --cov-append
        # ======= Utils Tests =============== #
        - pytest fitbenchmarking/utils --cov=fitbenchmarking/utils
          --cov-report term-missing --cov-append
      after_success:
        - coveralls
    - name: System Tests
      script:
        # ======= System Test =============== #
        - pytest fitbenchmarking/systests
